name: Deploy to WordPress.org
on:
  push:
    tags:
    - "*"
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: pxgamer/composer-action@master
      with:
        command: install --prefer-dist --no-dev --optimize-autoloader
    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@develop
      env:
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
